///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TestRailDemo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LoginShaw recording.
    /// </summary>
    [TestModule("8d5bfe48-e495-4b69-9b30-ecd74abfec80", ModuleType.Recording, 1)]
    public partial class LoginShaw : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TestRailDemoRepository repository.
        /// </summary>
        public static TestRailDemoRepository repo = TestRailDemoRepository.Instance;

        static LoginShaw instance = new LoginShaw();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LoginShaw()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LoginShaw Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://172.31.231.144:8443/ebx-ui/ui' with browser 'Chrome' in maximized mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://172.31.231.144:8443/ebx-ui/ui", "Chrome", "", false, true, false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShawQA.Https172312311448443EbxUiUi.LoginField' at Center.", repo.ShawQA.Https172312311448443EbxUiUi.LoginFieldInfo, new RecordItemIndex(1));
            repo.ShawQA.Https172312311448443EbxUiUi.LoginField.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ahathaw' with focus on 'ShawQA.Https172312311448443EbxUiUi.LoginField'.", repo.ShawQA.Https172312311448443EbxUiUi.LoginFieldInfo, new RecordItemIndex(2));
            repo.ShawQA.Https172312311448443EbxUiUi.LoginField.EnsureVisible();
            Keyboard.Press("ahathaw");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShawQA.Https172312311448443EbxUiUi.Password' at 53;17.", repo.ShawQA.Https172312311448443EbxUiUi.PasswordInfo, new RecordItemIndex(3));
            repo.ShawQA.Https172312311448443EbxUiUi.Password.Click("53;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ahathaw' with focus on 'ShawQA.Https172312311448443EbxUiUi.Password'.", repo.ShawQA.Https172312311448443EbxUiUi.PasswordInfo, new RecordItemIndex(4));
            repo.ShawQA.Https172312311448443EbxUiUi.Password.PressKeys("ahathaw");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShawQA.Https172312311448443EbxUiUi.LogInButton' at 12;3.", repo.ShawQA.Https172312311448443EbxUiUi.LogInButtonInfo, new RecordItemIndex(5));
            repo.ShawQA.Https172312311448443EbxUiUi.LogInButton.Click("12;3");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
