///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TestRailDemo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TestRailDemoRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("4f5d5f03-992b-4b7d-a3b4-9301e753ea5f")]
    public partial class TestRailDemoRepository : RepoGenBaseFolder
    {
        static TestRailDemoRepository instance = new TestRailDemoRepository();
        TestRailDemoRepositoryFolders.ShawQAAppFolder _shawqa;
        TestRailDemoRepositoryFolders.ShawQAGoogleChromeAppFolder _shawqagooglechrome;

        /// <summary>
        /// Gets the singleton class instance representing the TestRailDemoRepository element repository.
        /// </summary>
        [RepositoryFolder("4f5d5f03-992b-4b7d-a3b4-9301e753ea5f")]
        public static TestRailDemoRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TestRailDemoRepository() 
            : base("TestRailDemoRepository", "/", null, 0, false, "4f5d5f03-992b-4b7d-a3b4-9301e753ea5f", ".\\RepositoryImages\\TestRailDemoRepository4f5d5f03.rximgres")
        {
            _shawqa = new TestRailDemoRepositoryFolders.ShawQAAppFolder(this);
            _shawqagooglechrome = new TestRailDemoRepositoryFolders.ShawQAGoogleChromeAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("4f5d5f03-992b-4b7d-a3b4-9301e753ea5f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ShawQA folder.
        /// </summary>
        [RepositoryFolder("e440545c-f053-4839-bb7d-f716a66fc7b7")]
        public virtual TestRailDemoRepositoryFolders.ShawQAAppFolder ShawQA
        {
            get { return _shawqa; }
        }

        /// <summary>
        /// The ShawQAGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("a133c6f3-29bb-4d3b-9bc2-70a2584c0a2a")]
        public virtual TestRailDemoRepositoryFolders.ShawQAGoogleChromeAppFolder ShawQAGoogleChrome
        {
            get { return _shawqagooglechrome; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TestRailDemoRepositoryFolders
    {
        /// <summary>
        /// The ShawQAAppFolder folder.
        /// </summary>
        [RepositoryFolder("e440545c-f053-4839-bb7d-f716a66fc7b7")]
        public partial class ShawQAAppFolder : RepoGenBaseFolder
        {
            TestRailDemoRepositoryFolders.Https172312311448443EbxUiUiFolder _https172312311448443ebxuiui;
            TestRailDemoRepositoryFolders.EbxLegacyComponentFolder _ebxlegacycomponent;
            RepoItemInfo _burgermenuInfo;
            RepoItemInfo _shawfacilitymasterInfo;
            RepoItemInfo _workflowInfo;
            RepoItemInfo _workitemsInfo;
            RepoItemInfo _anthonyhathawayInfo;
            RepoItemInfo _logoutInfo;

            /// <summary>
            /// Creates a new ShawQA  folder.
            /// </summary>
            public ShawQAAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ShawQA", "/dom[@domain='172.31.231.144:8443']", parentFolder, 30000, null, false, "e440545c-f053-4839-bb7d-f716a66fc7b7", "")
            {
                _https172312311448443ebxuiui = new TestRailDemoRepositoryFolders.Https172312311448443EbxUiUiFolder(this);
                _ebxlegacycomponent = new TestRailDemoRepositoryFolders.EbxLegacyComponentFolder(this);
                _burgermenuInfo = new RepoItemInfo(this, "BurgerMenu", ".//div[#'_ebx-root']/div/div/div[1]//button[@title='Select perspective']/svg", "", 30000, null, "00adac5e-419a-4a9e-b9b9-74021a3489f9");
                _shawfacilitymasterInfo = new RepoItemInfo(this, "ShawFacilityMaster", "body//ul/ul[1]/li[3]/span[@innertext='Shaw Facility Master']", "", 30000, null, "c6b95a2a-eeb2-48ac-868a-d5282fdbddc2");
                _workflowInfo = new RepoItemInfo(this, "Workflow", ".//div[#'_ebx-root']/div/div/div[2]/div/div[1]/div/div[2]/div/div[1]//ul/li[3]/div[2]/div/div/?/?/span[@innertext='Workflow']", "", 30000, null, "31d4645d-d0f3-4d69-a7b0-956c0849eb92");
                _workitemsInfo = new RepoItemInfo(this, "WorkItems", ".//div[#'_ebx-root']/div/div/div[2]/div/div[1]/div/div[2]/div/div[1]//ul/ul[2]/li[1]/div[2]/a[@href>'https://172.31.231.144:84']/span[@innertext='Work Items']", "", 30000, null, "10074211-8a5c-4739-a512-4196e33cb0ff");
                _anthonyhathawayInfo = new RepoItemInfo(this, "AnthonyHathaway", ".//div[#'_ebx-root']/div/div/div[1]/div[2]//button[@innertext='Anthony Hathaway']", "", 30000, null, "58590f15-0057-4c5b-8dbf-434af65333e9");
                _logoutInfo = new RepoItemInfo(this, "Logout", "body/div[2]//button/span[@innertext='Logout']", "", 30000, null, "4b907fa5-b20f-4405-b7ee-cca3757fb200");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e440545c-f053-4839-bb7d-f716a66fc7b7")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e440545c-f053-4839-bb7d-f716a66fc7b7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BurgerMenu item.
            /// </summary>
            [RepositoryItem("00adac5e-419a-4a9e-b9b9-74021a3489f9")]
            public virtual Ranorex.SvgTag BurgerMenu
            {
                get
                {
                    return _burgermenuInfo.CreateAdapter<Ranorex.SvgTag>(true);
                }
            }

            /// <summary>
            /// The BurgerMenu item info.
            /// </summary>
            [RepositoryItemInfo("00adac5e-419a-4a9e-b9b9-74021a3489f9")]
            public virtual RepoItemInfo BurgerMenuInfo
            {
                get
                {
                    return _burgermenuInfo;
                }
            }

            /// <summary>
            /// The ShawFacilityMaster item.
            /// </summary>
            [RepositoryItem("c6b95a2a-eeb2-48ac-868a-d5282fdbddc2")]
            public virtual Ranorex.SpanTag ShawFacilityMaster
            {
                get
                {
                    return _shawfacilitymasterInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ShawFacilityMaster item info.
            /// </summary>
            [RepositoryItemInfo("c6b95a2a-eeb2-48ac-868a-d5282fdbddc2")]
            public virtual RepoItemInfo ShawFacilityMasterInfo
            {
                get
                {
                    return _shawfacilitymasterInfo;
                }
            }

            /// <summary>
            /// The Workflow item.
            /// </summary>
            [RepositoryItem("31d4645d-d0f3-4d69-a7b0-956c0849eb92")]
            public virtual Ranorex.SpanTag Workflow
            {
                get
                {
                    return _workflowInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Workflow item info.
            /// </summary>
            [RepositoryItemInfo("31d4645d-d0f3-4d69-a7b0-956c0849eb92")]
            public virtual RepoItemInfo WorkflowInfo
            {
                get
                {
                    return _workflowInfo;
                }
            }

            /// <summary>
            /// The WorkItems item.
            /// </summary>
            [RepositoryItem("10074211-8a5c-4739-a512-4196e33cb0ff")]
            public virtual Ranorex.SpanTag WorkItems
            {
                get
                {
                    return _workitemsInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The WorkItems item info.
            /// </summary>
            [RepositoryItemInfo("10074211-8a5c-4739-a512-4196e33cb0ff")]
            public virtual RepoItemInfo WorkItemsInfo
            {
                get
                {
                    return _workitemsInfo;
                }
            }

            /// <summary>
            /// The AnthonyHathaway item.
            /// </summary>
            [RepositoryItem("58590f15-0057-4c5b-8dbf-434af65333e9")]
            public virtual Ranorex.ButtonTag AnthonyHathaway
            {
                get
                {
                    return _anthonyhathawayInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The AnthonyHathaway item info.
            /// </summary>
            [RepositoryItemInfo("58590f15-0057-4c5b-8dbf-434af65333e9")]
            public virtual RepoItemInfo AnthonyHathawayInfo
            {
                get
                {
                    return _anthonyhathawayInfo;
                }
            }

            /// <summary>
            /// The Logout item.
            /// </summary>
            [RepositoryItem("4b907fa5-b20f-4405-b7ee-cca3757fb200")]
            public virtual Ranorex.SpanTag Logout
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Logout item info.
            /// </summary>
            [RepositoryItemInfo("4b907fa5-b20f-4405-b7ee-cca3757fb200")]
            public virtual RepoItemInfo LogoutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The Https172312311448443EbxUiUi folder.
            /// </summary>
            [RepositoryFolder("e3d72da7-b4cb-4182-8327-4ca6f557ed2a")]
            public virtual TestRailDemoRepositoryFolders.Https172312311448443EbxUiUiFolder Https172312311448443EbxUiUi
            {
                get { return _https172312311448443ebxuiui; }
            }

            /// <summary>
            /// The EbxLegacyComponent folder.
            /// </summary>
            [RepositoryFolder("872671a5-0169-4b99-852c-b11753955599")]
            public virtual TestRailDemoRepositoryFolders.EbxLegacyComponentFolder EbxLegacyComponent
            {
                get { return _ebxlegacycomponent; }
            }
        }

        /// <summary>
        /// The Https172312311448443EbxUiUiFolder folder.
        /// </summary>
        [RepositoryFolder("e3d72da7-b4cb-4182-8327-4ca6f557ed2a")]
        public partial class Https172312311448443EbxUiUiFolder : RepoGenBaseFolder
        {
            RepoItemInfo _loginbuttonInfo;
            RepoItemInfo _loginfieldInfo;
            RepoItemInfo _passwordInfo;

            /// <summary>
            /// Creates a new Https172312311448443EbxUiUi  folder.
            /// </summary>
            public Https172312311448443EbxUiUiFolder(RepoGenBaseFolder parentFolder) :
                    base("Https172312311448443EbxUiUi", ".//div[#'_ebx-root']/div/div/div[2]/form[@action='https://172.31.231.144:8443/ebx-ui/ui']", parentFolder, 30000, null, false, "e3d72da7-b4cb-4182-8327-4ca6f557ed2a", "")
            {
                _loginbuttonInfo = new RepoItemInfo(this, "LogInButton", ".//button/span[@innertext='Log in']", "", 30000, null, "a13c854d-5967-4a72-87b9-7dce5ec072b9");
                _loginfieldInfo = new RepoItemInfo(this, "LoginField", "div[1]/div[1]/?/?/input[@name='login']", "", 30000, null, "8a899662-b8eb-4054-9298-cda4fc7d3e75");
                _passwordInfo = new RepoItemInfo(this, "Password", "div[1]/div[2]/?/?/input[@name='password']", "", 30000, null, "0afb1fdd-2378-4304-9bf9-03ef72e22a10");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e3d72da7-b4cb-4182-8327-4ca6f557ed2a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e3d72da7-b4cb-4182-8327-4ca6f557ed2a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LogInButton item.
            /// </summary>
            [RepositoryItem("a13c854d-5967-4a72-87b9-7dce5ec072b9")]
            public virtual Ranorex.SpanTag LogInButton
            {
                get
                {
                    return _loginbuttonInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The LogInButton item info.
            /// </summary>
            [RepositoryItemInfo("a13c854d-5967-4a72-87b9-7dce5ec072b9")]
            public virtual RepoItemInfo LogInButtonInfo
            {
                get
                {
                    return _loginbuttonInfo;
                }
            }

            /// <summary>
            /// The LoginField item.
            /// </summary>
            [RepositoryItem("8a899662-b8eb-4054-9298-cda4fc7d3e75")]
            public virtual Ranorex.InputTag LoginField
            {
                get
                {
                    return _loginfieldInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginField item info.
            /// </summary>
            [RepositoryItemInfo("8a899662-b8eb-4054-9298-cda4fc7d3e75")]
            public virtual RepoItemInfo LoginFieldInfo
            {
                get
                {
                    return _loginfieldInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("0afb1fdd-2378-4304-9bf9-03ef72e22a10")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("0afb1fdd-2378-4304-9bf9-03ef72e22a10")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }
        }

        /// <summary>
        /// The EbxLegacyComponentFolder folder.
        /// </summary>
        [RepositoryFolder("872671a5-0169-4b99-852c-b11753955599")]
        public partial class EbxLegacyComponentFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ebxiconInfo;
            RepoItemInfo _applyInfo;
            RepoItemInfo _ebxsimplesearchfilternodeselectorlistfInfo;
            RepoItemInfo _ebxicon1Info;
            RepoItemInfo _offeredInfo;
            RepoItemInfo _offered1Info;

            /// <summary>
            /// Creates a new EbxLegacyComponent  folder.
            /// </summary>
            public EbxLegacyComponentFolder(RepoGenBaseFolder parentFolder) :
                    base("EbxLegacyComponent", ".//iframe[#'ebx-legacy-component']", parentFolder, 30000, null, false, "872671a5-0169-4b99-852c-b11753955599", "")
            {
                _ebxiconInfo = new RepoItemInfo(this, "EbxIcon", ".//button[#'ebx_filtersButton']/span", "", 30000, null, "ea34ed2b-267d-47b5-a434-ff30ff5c6b9e");
                _applyInfo = new RepoItemInfo(this, "Apply", ".//div[#'ebx_FilterBlockList']/?/?/form[@action='https://172.31.231.144:8443/ebx/']//button[@innertext='Apply']", "", 30000, null, "50a3aea1-d247-4ea7-911f-3314cd09470c");
                _ebxsimplesearchfilternodeselectorlistfInfo = new RepoItemInfo(this, "EbxSimpleSearchFilterNodeSelectorListF", ".//div[#'ebx_FilterBlockList']/?/?/form[@action='https://172.31.231.144:8443/ebx/']/div[3]//select[@name='ebx_SimpleSearchFilterNodeSelectorList_FILTER_0']", "", 30000, null, "d86fd92e-18e5-4bc6-99fc-c26cda3140e3");
                _ebxicon1Info = new RepoItemInfo(this, "EbxIcon1", ".//div[#'ebx_FilterBlockList']/div[1]/form[@action='https://172.31.231.144:8443/ebx/']/div[3]/div[1]/div[1]/div[1]/div/div/div/div/div[2]//button[@title='Open drop-down list']/span", "", 30000, null, "c69fe1bb-be42-4394-9418-c399d428fcf7");
                _offeredInfo = new RepoItemInfo(this, "Offered", ".//div[#'ebx_ISS_Results']/div[@innertext='Offered']", "", 30000, null, "f706a9ff-d288-41b1-8891-fffbbae35181");
                _offered1Info = new RepoItemInfo(this, "Offered1", ".//div[#'ebx_workspaceTable_mainScroller']//td[@innertext='Offered']", "", 30000, null, "61c18062-42a8-4c41-ad92-b2b279d0cef8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("872671a5-0169-4b99-852c-b11753955599")]
            public virtual Ranorex.IFrameTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.IFrameTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("872671a5-0169-4b99-852c-b11753955599")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EbxIcon item.
            /// </summary>
            [RepositoryItem("ea34ed2b-267d-47b5-a434-ff30ff5c6b9e")]
            public virtual Ranorex.SpanTag EbxIcon
            {
                get
                {
                    return _ebxiconInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The EbxIcon item info.
            /// </summary>
            [RepositoryItemInfo("ea34ed2b-267d-47b5-a434-ff30ff5c6b9e")]
            public virtual RepoItemInfo EbxIconInfo
            {
                get
                {
                    return _ebxiconInfo;
                }
            }

            /// <summary>
            /// The Apply item.
            /// </summary>
            [RepositoryItem("50a3aea1-d247-4ea7-911f-3314cd09470c")]
            public virtual Ranorex.ButtonTag Apply
            {
                get
                {
                    return _applyInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Apply item info.
            /// </summary>
            [RepositoryItemInfo("50a3aea1-d247-4ea7-911f-3314cd09470c")]
            public virtual RepoItemInfo ApplyInfo
            {
                get
                {
                    return _applyInfo;
                }
            }

            /// <summary>
            /// The EbxSimpleSearchFilterNodeSelectorListF item.
            /// </summary>
            [RepositoryItem("d86fd92e-18e5-4bc6-99fc-c26cda3140e3")]
            public virtual Ranorex.SelectTag EbxSimpleSearchFilterNodeSelectorListF
            {
                get
                {
                    return _ebxsimplesearchfilternodeselectorlistfInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The EbxSimpleSearchFilterNodeSelectorListF item info.
            /// </summary>
            [RepositoryItemInfo("d86fd92e-18e5-4bc6-99fc-c26cda3140e3")]
            public virtual RepoItemInfo EbxSimpleSearchFilterNodeSelectorListFInfo
            {
                get
                {
                    return _ebxsimplesearchfilternodeselectorlistfInfo;
                }
            }

            /// <summary>
            /// The EbxIcon1 item.
            /// </summary>
            [RepositoryItem("c69fe1bb-be42-4394-9418-c399d428fcf7")]
            public virtual Ranorex.SpanTag EbxIcon1
            {
                get
                {
                    return _ebxicon1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The EbxIcon1 item info.
            /// </summary>
            [RepositoryItemInfo("c69fe1bb-be42-4394-9418-c399d428fcf7")]
            public virtual RepoItemInfo EbxIcon1Info
            {
                get
                {
                    return _ebxicon1Info;
                }
            }

            /// <summary>
            /// The Offered item.
            /// </summary>
            [RepositoryItem("f706a9ff-d288-41b1-8891-fffbbae35181")]
            public virtual Ranorex.DivTag Offered
            {
                get
                {
                    return _offeredInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Offered item info.
            /// </summary>
            [RepositoryItemInfo("f706a9ff-d288-41b1-8891-fffbbae35181")]
            public virtual RepoItemInfo OfferedInfo
            {
                get
                {
                    return _offeredInfo;
                }
            }

            /// <summary>
            /// The Offered1 item.
            /// </summary>
            [RepositoryItem("61c18062-42a8-4c41-ad92-b2b279d0cef8")]
            public virtual Ranorex.TdTag Offered1
            {
                get
                {
                    return _offered1Info.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The Offered1 item info.
            /// </summary>
            [RepositoryItemInfo("61c18062-42a8-4c41-ad92-b2b279d0cef8")]
            public virtual RepoItemInfo Offered1Info
            {
                get
                {
                    return _offered1Info;
                }
            }
        }

        /// <summary>
        /// The ShawQAGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("a133c6f3-29bb-4d3b-9bc2-70a2584c0a2a")]
        public partial class ShawQAGoogleChromeAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ShawQAGoogleChrome  folder.
            /// </summary>
            public ShawQAGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ShawQAGoogleChrome", "/form[@title='Shaw QA - Google Chrome']", parentFolder, 30000, null, true, "a133c6f3-29bb-4d3b-9bc2-70a2584c0a2a", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a133c6f3-29bb-4d3b-9bc2-70a2584c0a2a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a133c6f3-29bb-4d3b-9bc2-70a2584c0a2a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
